### ISSUE TITLE
preprocessing Error

### ISSUE THREAD

**Issue by EEJQX** [matthi99/deepGMM#1]
Excuse me, i am sorry about troubling you.

When running 'python preprocessing.py'，error occor:

                   data2d['C0']=data['C0'][i,...]
 IndexError: index 2 is out of bounds for axis 0 with size 2

I check that C0 only has 2 channels，but LGE has 3 channel and T2 has 4 channel. 

Is my datasets has anypeoblem?

**Comment by matthi99** [comment]
Thats weird. C0, LGE and T2 should all have the same image sizes. What dataset did you use? On the MyoPS datset it should work without any problems.

**Comment by EEJQX** [comment]
> Thats weird. C0, LGE and T2 should all have the same image sizes. What dataset did you use? On the MyoPS datset it should work without any problems.

oh my god ! 
I use the same dataset with you and download from the link you provided. But i found the image size is funny hh,  i print their shape information

print(data['LGE'].shape)
print(data['T2'].shape)
print(data['C0'].shape)
print('ok')

and get like below:

(5, 485, 480)
(4, 408, 392)
(5, 479, 479)
ok
(3, 494, 492)
(4, 485, 478)
(2, 489, 498)
ok
(5, 477, 477)
(3, 499, 502)
(5, 477, 477)
ok
...

I would check the dataset i used, thanks again~

**Comment by EEJQX** [comment]
could you please send me the data before preprocessing? my email is ee_jqx@163.com.

thanks~

**Comment by matthi99** [comment]
It seems you are loading LGE, T2 and C0 from different patients. Have you changed the filenames? When you print the shapes it should look like this:
(5, 478, 482)
(5, 478, 482)
(5, 478, 482)
ok
(3, 511, 511)
(3, 511, 511)
(3, 511, 511)
ok
(3, 483, 471)
(3, 483, 471)
(3, 483, 471)
ok
(6, 481, 478)
(6, 481, 478)
(6, 481, 478)
...
Your filelists schould look like this:
files_LGE= ['DATA\\MyoPS 2020 Dataset/train25/myops_training_101_DE.nii.gz', 'DATA\\MyoPS 2020 Dataset/train25/myops_training_102_DE.nii.gz',...]
files_T2= ['DATA\\MyoPS 2020 Dataset/train25/myops_training_101_T2.nii.gz', 'DATA\\MyoPS 2020 Dataset/train25/myops_training_102_T2.nii.gz',...]
files_C0= ['DATA\\MyoPS 2020 Dataset/train25/myops_training_101_C0.nii.gz', 'DATA\\MyoPS 2020 Dataset/train25/myops_training_102_C0.nii.gz',...]

Unfortunately I cannot email you the whole dataset since it exceeds the maximum file size that I can send per email.

**Comment by EEJQX** [comment]
> It seems you are loading LGE, T2 and C0 from different patients. Have you changed the filenames? When you print the shapes it should look like this: (5, 478, 482) (5, 478, 482) (5, 478, 482) ok (3, 511, 511) (3, 511, 511) (3, 511, 511) ok (3, 483, 471) (3, 483, 471) (3, 483, 471) ok (6, 481, 478) (6, 481, 478) (6, 481, 478) ... Your filelists schould look like this: files_LGE= ['DATA\MyoPS 2020 Dataset/train25/myops_training_101_DE.nii.gz', 'DATA\MyoPS 2020 Dataset/train25/myops_training_102_DE.nii.gz',...] files_T2= ['DATA\MyoPS 2020 Dataset/train25/myops_training_101_T2.nii.gz', 'DATA\MyoPS 2020 Dataset/train25/myops_training_102_T2.nii.gz',...] files_C0= ['DATA\MyoPS 2020 Dataset/train25/myops_training_101_C0.nii.gz', 'DATA\MyoPS 2020 Dataset/train25/myops_training_102_C0.nii.gz',...]
> 
> Unfortunately I cannot email you the whole dataset since it exceeds the maximum file size that I can send per email.

OH!!!! You are right! thank you very much~!
